# Custom aliases
alias rm='rm -Iv'
alias cls='clear'
alias free='free -h'
alias df='df -h'
alias du='du -h'
alias mkdir='mkdir -p'
alias yout='youtube-dl -f 140'
alias gradlew='./gradlew'
alias xclip='xclip -selection clipboard'
alias alien='alien -r'
